### PR TITLE
Score

### PR DESCRIPTION
**Pull request by wjduand**
display score

### CODE REVIEW

**Comment by hammockt** [comment]
Sorry but it still has merge conflicts.

**Comment by wjduand** [comment]
I know I'm still trying to solve that, what did you do last time?

**Comment by hammockt** [comment]
I updated my repository and pulled before I made my commits. is it up to date?

**Comment by wjduand** [comment]
i don't think so, how did you update?

**Comment by duffinp** [comment]
This conflicts with my commits as I was also working extensively with the AcesUp.html file. Merge it using Source Tree or something like that.

**Pull request closed without merging**
